name: Test script
on: 
  push: 
    branches:
    - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Download node for Javascript
        run: sudo apt update && sudo apt install -y nodejs && sudo apt install -y npm
      - run: echo "node has been installed" 
      
      - name: Start script
        run: |
          pwd
          ls -la
          node hello.js > console.log
          touch /tmp/exit_script.log
          ls -la
 
      - name: Upload command output
        uses: actions/upload-artifact@v1
        with:
          path: console.log 
      
