name: Test script
on: 
  push: 
    branches:
    - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      #- name: Download node for Javascript
      #  run: sudo apt update && sudo apt install -y nodejs && sudo apt install -y npm
      #- run: echo "node has been installed" 
      
      - name: Start script
        run: |
          pwd
          ls -la
          echo "console.log("Hello, GitHub Actions!")" > hello.js
          chmod +x hello.js
          node hello.js
          echo "Script executed successfully"
 
      - name: Upload command output
        uses: actions/upload-artifact@v2

      
